# Generated by Django 6.0 on 2025-12-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_category_task_priority_subtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Подзадача', 'verbose_name_plural': 'Подзадачи'},
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начата'), ('in_progress', 'В процессе'), ('done', 'Выполнена'), ('blocked', 'Заблокирована')], default='not_started', max_length=20, verbose_name='Статус подзадачи'),
        ),
    ]
