# Generated by Django 6.0 on 2026-01-10 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_category_deleted_at_category_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения подзадачи'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена?'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtask_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец подзадачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена?'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец задачи'),
        ),
    ]
