"""
Django settings for HW project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r#3t%5cgk)^#eyr@_fry_0=@a#%i_mjz-y9#%4ydr8urkfv0$9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Сторонние приложения
    'rest_framework',
    'rest_framework_simplejwt',  # ЗАДАНИЕ 1: JWT аутентификация
    'django_filters',
    'drf_yasg',

    # Мои приложения
    'task_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HW.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HW.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ======================================================================
# ЗАДАНИЕ 1: НАСТРОЙКА JWT АУТЕНТИФИКАЦИИ
# ======================================================================
"""
Установите: pip install djangorestframework-simplejwt
"""

REST_FRAMEWORK = {
    # ==================== ЗАДАНИЕ 1: JWT АУТЕНТИФИКАЦИЯ ====================
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT токены
        'rest_framework.authentication.SessionAuthentication',        # Сессии
        'rest_framework.authentication.BasicAuthentication',          # Basic auth
    ],

    # ==================== ЗАДАНИЕ 2: ПЕРМИШЕНЫ ПО УМОЛЧАНИЮ ====================
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Чтение для всех, запись только авторизованным
    ],

    # ==================== ЗАДАНИЕ 3: ГЛОБАЛЬНАЯ ПАГИНАЦИЯ ====================
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,  # 5 элементов по умолчанию

    # ==================== ФИЛЬТРАЦИЯ ====================
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# ==================== НАСТРОЙКИ SIMPLE JWT ====================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),     # Время жизни access токена
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),        # Время жизни refresh токена
    'ROTATE_REFRESH_TOKENS': True,                      # Обновлять refresh токены
    'BLACKLIST_AFTER_ROTATION': True,                   # Блокировать старые refresh токены
    'UPDATE_LAST_LOGIN': True,                          # Обновлять последний вход

    'ALGORITHM': 'HS256',                               # Алгоритм шифрования
    'SIGNING_KEY': SECRET_KEY,                          # Ключ для подписи
    'VERIFYING_KEY': None,                              # Ключ для проверки

    'AUTH_HEADER_TYPES': ('Bearer',),                   # Тип заголовка для токена
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',           # Имя заголовка
    'USER_ID_FIELD': 'id',                              # Поле для идентификации пользователя
    'USER_ID_CLAIM': 'user_id',                         # Claim для user_id

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',                                 # Unique identifier claim

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# ======================================================================
# ЛОГИРОВАНИЕ (из предыдущего задания)
# ======================================================================
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
        'http_file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'http_logs.log',
            'formatter': 'verbose',
            'level': 'INFO',
        },
        'db_file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'db_logs.log',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
    },

    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['http_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['db_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}